# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fca64be22cee723c229b7effd9a64cafc8e7bb700efc6bfb901fdf4d5b89cd667c9c81cb0dad7a632aef95b89a730de594eb0a687259d34fc8f6e661c84beeb

test:
  secret_key_base: b444d727411d050911a456b917895dcadd9388848f6c855e932466a1d48f0791c3dad021e71885c12432121ed1e6eb6101f27e7b2c01da716c5bafc395d455dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
